#!/bin/bash
###########
# LTC Trade Optimizer
# v.01

# ltc_trade_optimizer shows optimal Litecoin trade permutations across various exchanges and trade permutations.
# Current exchange rates come from the BTC-E & Mt. Gox live tickers.

# Please donate and contact meba for help or feedback on the IRC freenode server in #litecoin
#   LTC LNMsFNyNP2WUXAoBMWjSSVccsff8snC2HK
#   BTC 17uYo47rnCBEso9VXehLuU3c2D3PPBisak


# All the things!?
if [ ! $1 ]; then
  echo "derp: need LTC value"
  echo "  usage: $0 n"
  echo "    eg. \"$0 100\""
  exit
fi


# Whatch'a got?
ltc=$1


# Where's what? ..tickers
json_btce_btc2usd=https://btc-e.com/api/2/btc_usd/ticker
json_btce_ltc2btc=https://btc-e.com/api/2/ltc_btc/ticker
json_btce_ltc2usd=https://btc-e.com/api/2/ltc_usd/ticker
json_mtgox_btc2usd=https://data.mtgox.com/api/2/BTCUSD/money/ticker


# Colors
txtrst="$(tput sgr0)"
txtBlack="$(tput setaf 0)"
txtBlackBg="$(tput setab 0)"
txtDarkGrey="$(tput bold ; tput setaf 0)"
txtLightGrey="$(tput setaf 7)"
txtLightGreyBG="$(tput setab 7)"
txtWhite="$(tput bold ; tput setaf 7)"
txtRed="$(tput setaf 1)"
txtRedBG="$(tput setab 1)"
txtLightRed="$(tput bold ; tput setaf 1)"
txtGreen="$(tput setaf 2)"
txtGreenBG="$(tput setab 2)"
txtLightGreen="$(tput bold ; tput setaf 2)"
txtBrown="$(tput setaf 3)"
txtBrownBG="$(tput setab 3)"
txtYellow="$(tput bold ; tput setaf 3)"
txtBlue="$(tput setaf 4)"
txtBlueBG="$(tput setab 4)"
txtBrightBlue="$(tput bold ; tput setaf 4)"
txtPurple="$(tput setaf 5)"
txtPurpleBG="$(tput setab 5)"
txtPink="$(tput bold ; tput setaf 5)"
txtCyan="$(tput setaf 6)"
txtCyanBG="$(tput setab 6)"
txtBrightCyan="$(tput bold ; tput setaf 6)"


# hi..
echo
echo -e "LTC Trade Optimizer"


# Fees
fee_btce_transaction=.002
  fbt=$fee_btce_transaction
  fbtp=$(echo "${fbt} * 100" \
    | bc \
    | awk '{printf "%f", $0}' \
    | awk 'sub("\\.*0+$","")') # percentage

fee_mtgox_transaction=.006
  fmt=$fee_mtgox_transaction
  fmtp=$(echo "${fmt} * 100" \
    | bc \
    | awk '{printf "%f", $0}' \
    | awk 'sub("\\.*0+$","")') # percentage

fee_btce_withdraw_btc=.01
  fbwb=$fee_btce_withdraw_btc

fee_btce_withdraw_ltc=.5
  fbwl=$fee_btce_withdraw_ltc


# Exchanges..
exchange_btce_btc2usd=$(curl -s ${json_btce_btc2usd} \
  | python -mjson.tool \
  | grep sell \
  | awk -F: '{print $2}' \
  | sed -e 's/\ //g' -e 's/,//g')
  ebbu=$exchange_btce_btc2usd

exchange_btce_ltc2btc=$(curl -s ${json_btce_ltc2btc} \
  | python -mjson.tool \
  | grep sell \
  | awk -F: '{print $2}' \
  | sed -e 's/\ //g' -e 's/,//g')
  eblb=$exchange_btce_ltc2btc

exchange_btce_ltc2usd=$(curl -s ${json_btce_ltc2usd} \
  | python -mjson.tool \
  | grep sell \
  | awk -F: '{print $2}' \
  | sed -e 's/\ //g' -e 's/,//g')
  eblu=$exchange_btce_ltc2usd

exchange_mtgox_btc2usd=$(curl -s ${json_mtgox_btc2usd} \
  | python -mjson.tool \
  | grep -A 6 now \
  | grep value\" \
  | awk -F: '{print $2}' \
  | sed -e 's/\ //g' -e 's/,//g' -e 's/"//g')
  embu=$exchange_mtgox_btc2usd


# Conversions
btc_is_ltc=$(echo "1 / ${eblb}" | bc)
  bil=$btc_is_ltc

convert_btce_ltc2btc=$(echo "${ltc} * ${eblb}" | bc)
  cblb=$convert_btce_ltc2btc

convert_btce_ltc2usd=$(echo "${ltc} * ${eblu}" | bc)
  cblu=$convert_btce_ltc2usd

convert_btce_btc2usd=$(echo "${cblb} * ${ebbu}" | bc)
  cbbu=$convert_btce_btc2usd

convert_mtgox_btc2usd=$(echo "${cblb} * ${embu}" | bc)
  cmbu=$convert_mtgox_btc2usd


# Fee calculations
fbt_calculation=$(echo "${fbt} * ${ltc}" | bc)
  fbtcl=$fbt_calculation # LTC
  fbtcb=$(echo "${fbt} * ${cblb}" | bc) # BTC
  fbtcu=$(echo "${fbtcl} * ${eblu}" | bc) # USD

fmt_calculation=$(echo "${fmt} * ${cblb}" | bc)
  fmtcb=$fmt_calculation # BTC
  fmtcu=$(echo "${fmtcb} * ${embu}" | bc) # USD


# Trade Permutations
trade_btce_ltc2usd=$(echo "${cblu} - ${fbtcu}" | bc)
  tblu=$trade_btce_ltc2usd

trade_btce_ltc2btc2usd=$(echo "${tblu} - ${fbtcu}" | bc)
  tblbu=$trade_btce_ltc2btc2usd

trade_btce_ltc2btc=$(echo "${cblb} - ${fbtcb}" | bc)
  tblb=$trade_btce_ltc2btc

trade_btce_ltc2btc_mtgox_btc2usd=$(echo "((${cblb} - ${fbtcb} - ${fbwb}) * ${embu}) - ${fmtcu}" | bc)
  tblbmbu=$trade_btce_ltc2btc_mtgox_btc2usd


# Price sheet..
echo -e "  Fees"
echo -e "    BTC-E transaction fee at ${txtYellow}${fbtp}${txtrst}%	BTC ${txtRed}${fbtcb}${txtrst}, USD ${txtRed}${fbtcu}${txtrst}, LTC ${txtRed}${fbtcl}${txtrst}"
echo -e "    Mt.Gox transaction fee at ${txtYellow}${fmtp}${txtrst}%	BTC ${txtRed}${fmtcb}${txtrst}, USD ${txtRed}${fmtcu}${txtrst}"
echo
echo -e "    BTC-E withdrawl fee is flat-rate	BTC ${txtRed}${fbwb}${txtrst}, LTC ${txtRed}${fbwl}${txtrst}"
echo
echo -e "  Rates on ${txtPurple}$(date)${txtrst} (${txtCyan}1${txtrst} BTC = ${txtCyan}${bil}${txtrst} LTC)"
echo -e "    BTC-E: 	BTC/USD @ ${txtBlue}${ebbu}${txtrst}, LTC/USD @ ${txtBlue}${eblu}${txtrst}, LTC/BTC @ ${txtBlue}${eblb}${txtrst}" 
echo -e "    Mt.Gox:	BTC/USD @ ${txtBlue}${embu}${txtrst}"
echo
echo -e "  Conversion of ${txtCyan}${ltc}${txtrst} LTC"
echo -e "    BTC-E (LTC/BTC)	BTC ${txtGreen}${cblb}${txtrst}"
echo -e "    BTC-E (LTC/USD)	USD ${txtGreen}${cblu}${txtrst}"
echo -e "    BTC-E (BTC/USD)	USD ${txtGreen}${cbbu}${txtrst}"
echo -e "    Mt.Gox (BTC/USD)	USD ${txtGreen}${cmbu}${txtrst}"
echo
echo -e "  Trade Permutations (showing fees)"
echo -e "    BTC-E::LTC/BTC"
echo -e "      ${txtDarkGrey}LTC --(transaction fee)--> BTC${txtrst}"
echo -e "      (${txtCyan}L${ltc}${txtrst} * ${txtBlue}${eblb}${txtrst}) - ${txtRed}B${fbtcb}${txtrst} = ${txtGreen}B${tblb}${txtrst}" 
echo
echo -e "    BTC-E::LTC/USD"
echo -e "      ${txtDarkGrey}LTC --(transaction fee)--> USD${txtrst}"
echo -e "      (${txtCyan}L${ltc}${txtrst} * ${txtBlue}${eblu}${txtrst}) - ${txtRed}\$${fbtcu}${txtrst} = ${txtGreen}\$${tblu}${txtrst}" 
echo
echo -e "    BTC-E::LTC/BTC/USD"
echo -e "      ${txtDarkGrey}LTC --(transaction fee)--> BTC --(transaction fee)--> USD${txtrst}"
echo -e "      (((${txtCyan}L${ltc}${txtrst} * ${txtBlue}${eblb}${txtrst}) - ${txtRed}B${fbtcb}${txtrst}) * ${txtBlue}${ebbu}${txtrst}) - ${txtRed}\$${fbtcu}${txtrst} = ${txtGreen}\$${tblbu}${txtrst}" 
echo
echo -e "    BTC-E::LTC/BTC --> Mt.Gox::BTC/USD"
echo -e "      ${txtDarkGrey}LTC --(transaction fee)--> BTC --(withdrawl fee)--> Mt.Gox BTC --(transaction fee)--> USD${txtrst}"
echo -e "      (((${txtCyan}L${ltc}${txtrst} * ${txtBlue}${eblb}${txtrst}) - ${txtRed}B${fbtcb}${txtrst} - ${txtRed}B${fbwb}${txtrst}) * ${txtBlue}${embu}${txtrst}) - ${txtRed}\$${fmtcu}${txtrst} = ${txtGreen}\$${tblbmbu}${txtrst}"
echo
echo
echo -e "  ${txtDarkGrey}Please donate and contact meba for help or feedback on the IRC freenode server in #litecoin${txtrst}"
echo -e "    ${txtBrown}LTC LNMsFNyNP2WUXAoBMWjSSVccsff8snC2HK${txtrst}"
echo -e "    ${txtBrown}BTC 17uYo47rnCBEso9VXehLuU3c2D3PPBisak${txtrst}"
echo
